f = open('theorems.ell')
out = open('snippets.json', 'w')
out.write('{\n')
lines = f.readlines()
for line in lines:
    (id, name, thm) = line.strip().split('\t')
    out.write(f'\t"{thm}":'' {\n')
    out.write(f'\t\t"scope":"ell",\n')
    out.write(f'\t\t"prefix":"z{id}\\t{name}",\n')
    out.write(f'\t\t"body": [\n')
    out.write(f'\t\t\t"{id}\\t{name}\\t{thm}"\n')
    out.write(f'\t\t]\n')
    out.write('\t},\n')
f.close()
f = open('final_snippets.json')
text = f.read()
out.write(text)
out.close()
