f = open('theorems.ell')
out = open('snippets.json', 'w')
out.write('{\n')
lines = f.readlines()
for line in lines:
    (axiom, id, name, thm) = line.strip().split('@')
    out.write(f'\t"{thm}":'' {\n')
    out.write(f'\t\t"scope":"log",\n')
    out.write(f'\t\t"prefix":"z{id}\\t{name}",\n')
    out.write(f'\t\t"body": [\n')
    out.write(f'\t\t\t"{id:9}')
    if axiom != '':
        out.write(f'[{name}]' + ' '*(17 - len(name)))
    else:
        out.write(f'{name:19}')
    out.write(f'{thm}\\n"\n')
    out.write(f'\t\t]\n')
    out.write('\t},\n')
f.close()
f = open('final_snippets.json')
text = f.read()
out.write(text)
out.close()
